module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.campsiteDescriptions = [
    "Nestled in a peaceful forest, this campsite offers tranquility and a serene escape from the hustle and bustle of everyday life.",
    "Scenic views abound at this campsite, where you can enjoy stunning vistas of the surrounding mountains and valleys.",
    "Secluded and private, this campsite is perfect for those looking to get away from it all and immerse themselves in nature.",
    "Bathe in the warm sunlight at this sunny campsite, ideal for basking in the glow of a beautiful day.",
    "Feel the refreshing breeze at this breezy campsite, where the gentle wind adds a soothing touch to your outdoor experience.",
    "Set amidst a dense forest, this campsite is a haven for nature lovers and offers a true woodland adventure.",
    "Perched on a mountainside, this campsite provides breathtaking panoramic views and a thrilling mountain experience.",
    "Relax by the water at this lakefront campsite, perfect for swimming, fishing, and enjoying the serene lakeside environment.",
    "Listen to the gentle flow of the river at this riverside campsite, where the calming sounds of water create a peaceful atmosphere.",
    "Cozy and inviting, this campsite offers a warm and welcoming environment for families and friends to gather.",
    "Quiet and undisturbed, this campsite is ideal for those seeking solitude and a chance to unwind in a peaceful setting.",
    "Experience rustic charm at this campsite, where the simple joys of outdoor living are celebrated.",
    "Discover the wild beauty of this campsite, located in a remote area that offers untamed natural surroundings.",
    "Hidden away from the main trails, this campsite provides a secret retreat for those looking to escape the crowds.",
    "Marvel at the majestic scenery at this campsite, where towering trees and stunning landscapes create a magical ambiance.",
    "Far from the beaten path, this remote campsite offers a true backcountry experience for adventurous souls.",
    "Enjoy the cool shade at this shady campsite, perfect for escaping the heat and relaxing under the trees.",
    "Set on rolling hills, this campsite offers a unique and varied terrain for exploring and enjoying the outdoors.",
    "Spacious and open, this campsite provides plenty of room for activities and a sense of freedom in nature.",
    "Tranquil and calm, this campsite is a perfect spot for meditative moments and quiet reflection.",
    "Surrounded by lush, verdant greenery, this campsite is a paradise for those who love the vibrant colors of nature.",
    "For the adventurous spirit, this campsite offers exciting opportunities for exploration and outdoor activities.",
    "Experience the untamed wilderness at this campsite, where nature is at its most raw and beautiful.",
    "Discover the beauty of the backcountry at this campsite, perfect for those who love to hike and explore off the beaten path.",
    "Open and airy, this campsite provides a sense of space and freedom under the wide-open sky.",
    "Immerse yourself in the woodland environment at this campsite, surrounded by trees and the sounds of nature.",
    "Located in a peaceful valley, this campsite offers a serene and sheltered setting for your outdoor adventures.",
    "Gaze at the starry night sky at this campsite, where the lack of light pollution provides a perfect stargazing opportunity.",
    "Watch the sun set over the horizon at this campsite, offering stunning views and a perfect end to your day.",
    "Enjoy the panoramic views at this campsite, where you can see for miles and take in the beauty of the landscape.",
    "Feel the gentle touch of the wind at this windswept campsite, adding a refreshing element to your stay.",
    "Set among rocky terrain, this campsite offers a rugged and adventurous environment for exploration.",
    "Surrounded by grassy meadows, this campsite is perfect for picnics and enjoying the open fields.",
    "Experience the glistening beauty of this campsite, where the morning dew and sunlight create a sparkling environment.",
    "Hidden away from the main trails, this campsite offers a secret retreat for those looking to escape the crowds.",
    "Enter an enchanted world at this campsite, where the magical surroundings create a fairy-tale experience.",
    "Bask in the sun-dappled light at this campsite, where the trees create beautiful patterns of light and shadow.",
    "Serene and peaceful, this campsite offers a calming environment perfect for relaxation and meditation.",
    "Surrounded by blooming wildflowers, this campsite is a vibrant and colorful haven for nature lovers.",
    "Stay cool and comfortable at this campsite, where the shaded areas provide relief from the heat."
]
